cmake_minimum_required(VERSION 3.8)
project(go2_house_world)
find_package(ament_cmake REQUIRED)
install(DIRECTORY models worlds DESTINATION share/${PROJECT_NAME})
install(FILES README.md DESTINATION share/${PROJECT_NAME})
if(BUILD_TESTING)
  find_package(ament_cmake_pytest REQUIRED)
  ament_add_pytest_test(world_resources test/test_world_resources.py)
endif()
ament_package()
